### ISSUE TITLE
Null pointer exception 

### ISSUE THREAD

**Issue by anayyar82** [AndreSchumacher/avro-parquet-spark-example#2]
Hello While running with Array of object in Avro file getting Null pointer exception. 

Exception in thread "main" java.lang.NullPointerException
    at parquet.avro.AvroWriteSupport.fromAvroString(AvroWriteSupport.java:281)
    at parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:260)
    at parquet.avro.AvroWriteSupport.access$400(AvroWriteSupport.java:46)
    at parquet.avro.AvroWriteSupport$TwoLevelListWriter.writeCollection(AvroWriteSupport.java:456)
    at parquet.avro.AvroWriteSupport$ListWriter.writeList(AvroWriteSupport.java:305)
    at parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:266)
    at parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:167)
    at parquet.avro.AvroWriteSupport.writeRecord(AvroWriteSupport.java:149)
    at parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:262)
    at parquet.avro.AvroWriteSupport.access$400(AvroWriteSupport.java:46)
    at parquet.avro.AvroWriteSupport$TwoLevelListWriter.writeCollection(AvroWriteSupport.java:456)
    at parquet.avro.AvroWriteSupport$ListWriter.writeList(AvroWriteSupport.java:305)
    at parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:266)
    at parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:167)
    at parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:142)
    at parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:116)
    at parquet.hadoop.ParquetWriter.write(ParquetWriter.java:324)

**Comment by anayyar82** [comment]
Can you please tell if we need to read multiple files , how to read that, e.g. i want to read directory with multiple files. 

Thanks in advance for the help.

**Comment by anayyar82** [comment]
any update to read multiple avro files
